name: build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [RelWithDebInfo]
        enable_ui: [ on ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      if: runner.os == 'Linux'
      with:
        key: ${{ matrix.os }}-${{ matrix.enable_ui }}
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get update -qq
          sudo apt-get install -y \
            g++ clang-10 libc++-10-dev libc++abi-10-dev cmake ninja-build libx11-dev \
            libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev unzip
        fi
    - name: Get skia
      shell: bash
      run: |
        mkdir -p build
        cd build
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          wget -O skia.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libc++.zip
          mkdir -p skia
          unzip skia.zip -d skia/
        else
          mkdir -p skia
          powershell.exe -File get_skia.ps1
        fi

    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DENABLE_TESTS=ON \
            -DENABLE_UI=${{ matrix.enable_ui }} \
            -DENABLE_CCACHE=$enable_ccache \
            -DWEBP_LIBRARIES=libwebp \
            -DLAF_BACKEND=skia -DSKIA_DIR=./skia  -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
        else
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DENABLE_TESTS=ON \
            -DENABLE_UI=${{ matrix.enable_ui }} \
            -DENABLE_CCACHE=$enable_ccache \
            -DWEBP_LIBRARIES=libwebp \
            -DLAF_BACKEND=skia -DSKIA_DIR=./skia  -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 -DSKIA_LIBRARY=./skia/out/Release-x64/libskia.a
        fi
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja
    - name: Publish
      shell: bash
      env:
        GITEA_API_KEY: ${{ secrets.GITEA_API_KEY }}
      run: |
        cd build/bin

        tar -czvf aseprite.${{ runner.os }}.tar.gz aseprite* data/

        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          pip install requests
        fi

        python3 ../../push_gitea_release.py aseprite.${{ runner.os }}.tar.gz ${GITEA_API_KEY} ${GITHUB_REF_NAME}
